### PR TITLE
Fix duplicate query items.

### PR DESCRIPTION
**Pull request by calebd**

### CODE REVIEW

**Comment by calebd** [comment]
Tests pass. Can you review @cocoahero?

**Comment by calebd** [comment]
Thanks for pointing this out @arturgrigor!

**Comment by arturgrigor** [comment]
Sure, glad I could help. Can you also add support for CocoaPods in another PR?

**Comment by calebd** [comment]
Sure! I'll cherry-pick your commit in a separate pull request.

**Comment by arturgrigor** [comment]
Excellent! Thanks!

**Comment by cocoahero** [comment]
:+1:

**Pull request merged**
