### PR TITLE
CocoaPods support and minor fixes.

### PR DESCRIPTION
**Pull request by arturgrigor**
Can you accept this PR and also submit the pod to the official repo?

Also, before submitting it you must change some parameters from the `Iris.podspec` file, like the `s.source` URL.

### CODE REVIEW

**Comment by arturgrigor** [comment]
Also, please check the commit 689158aa3340ae230457e03aa1750ad52c3e9aaf to see whether it's ok to leave the `width` and `height` properties as `Int` or to revert them to `CGFloat` and change the `String` formatter to show the values as `Int`.

**Comment by cocoahero** [comment]
From the [Imgix docs](https://www.imgix.com/docs/reference/size#param-w):

> The width of the output image. Must be a positive integer or a float between 0.0 and 1.0, inclusive.
> 
> If the w parameter is an integer greater than 1, the value is interpreted as a pixel width. The resulting image will be w pixels tall.
> 
> If the w parameter is a float between 0.0 and 1.0, the value is interpreted as a ratio in relation to the source image size. For example, a w parameter set to 1.0 will result in the same output image width as the input, whereas a w value of 0.5 will result in an output image half the width of the input image.

It would appear to me that both integers and floats are valid values, although their valid ranges differ. Changing the type to `Int` removes the possibility of the `0.0...1.0` option which is not ideal. Leaving the properties as `CGFloat` allows the user to decide which "sizing method" to use. I think the best solution to this is better documentation.

As for the query items fix, thanks! Can you add a test case for it?

**Comment by arturgrigor** [comment]
Sure, I will update the test cases a little bit later.

**Comment by calebd** [comment]
Please submit individual pull requests for each of these. Closing and working on #3 separately.

**Pull request closed without merging**
